AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  saveMyBooks:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: saveMyBooks
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::451537815161:role/LambdaAccessRole'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /saveBooks
            Method: POST
      Environment:
        Variables:
          TABLE_NAME: MyBookShelf